apiVersion: v2
name: cloudbeaver
description: Cloud Database Manager
type: application
version: 1.1.1
appVersion: 25.3.0
dependencies:
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.36.0
maintainers:
  - name: Brawdunoir
    email: yann.lacroix@avisto.com
icon: https://github.com/dbeaver/cloudbeaver/wiki/images/cloudbeaver-head.png
annotations:
  artifacthub.io/signKey: |
    fingerprint: AF455B903BFED8363C003F9A5E2474CA7617EC66
    url: https://keybase.io/avistotelecom/pgp_keys.asc
